name: a2ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  firebase_ai: ^3.6.1
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  genui: ^0.6.0
  genui_firebase_ai: ^0.6.0
  google_fonts: ^6.3.3
  json_schema_builder: ^0.1.3
  logging: ^1.3.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
