name: a2ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+001

environment:
  sdk: ^3.10.0

dependencies:
  bloc: ^9.1.0
  firebase_ai: ^3.6.1
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  genui: ^0.6.0
  genui_firebase_ai: ^0.6.0
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  gpt_markdown: ^1.1.5
  json_schema_builder: ^0.1.3
  logging: ^1.3.0
  meta: ^1.17.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/travel_images/
    - assets/booking_service/
